# Generated by Django 5.1.2 on 2024-11-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='price',
            new_name='prices',
        ),
    ]
